# Generated by Django 6.0.6 on 2026-08-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_candidate_address_remove_candidate_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
