# Generated by Django 6.0.6 on 2026-10-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_job_featured'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='core_job_status_fa2791_idx'),
        ),
    ]
