# Generated by Django 6.0.6 on 2026-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_required',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
