# Generated by Django 6.0.6 on 2026-10-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_job_education_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField(default=0)),
                ('skills_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('education_score', models.FloatField(blank=True, null=True)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_score', to='core.application')),
            ],
        ),
    ]
