# Generated by Django 6.0.6 on 2026-10-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_atsscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ats_cutoff',
            field=models.FloatField(default=70.0),
        ),
    ]
